pipeline {
    agent any

    tools {
        maven "MAVEN3"
        jdk "jdk17"
    }

    environment {
        cluster = "vproappProd"
        service = "vprofileapptask-service-Prod"
    }

    stages {

        stage('Deploy to Prod ECS') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh '''
                    aws ecs update-service \
                    --cluster ${cluster} \
                    --service ${service} \
                    --force-new-deployment
                    '''
                }
            }
        }

    }
}